### ISSUE TITLE
error while deploy mongodb-enterprise-operator.yaml

### ISSUE THREAD

**Issue by abinasroy** [mongodb/mongodb-enterprise-kubernetes#112]
getting below error while deploy mongodb-enterprise-operator.yaml.

{"level":"fatal","ts":......,"caller":"ops-manager-kubernetes/main.go:91","msg":"Get https://XXXXX:443/api?timeout=32s: dial tcp XXXX:443: connect: connection refused","stacktrace":"main.main\n\t/data/mci/14240afe05ad215b52658b5a8eb4465c/src/github.com/10gen/ops-manager-kubernetes/main.go:91\nruntime.main\n\t/opt/golang/go1.13/src/runtime/proc.go:203"}.

**Comment by antonlisovenko** [comment]
@abinasroy thanks for your report

This looks like some connectivity issue and could be a temporary glitch maybe?
Do you still have this problem or you managed to get it working?

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
