### ISSUE TITLE
failed to create symbolic link '/data/journal': Permission denied

### ISSUE THREAD

**Issue by jatalocks** [mongodb/mongodb-enterprise-kubernetes#116]
The MongoDBOpsManager CRD created the StatefulSet which creates the "mongodb-opsmanager-db-0" pod. This pod binds to either a SINGULAR or MULTIPLE PVCs using persistence. Both approaches produce the error inside the ops manager pod:

`failed to create symbolic link '/data/journal': Permission denied`

I've tried to install the operator on multiple cloud providers (public Azure cloud and private VMware cloud), using either singular and multiple pvc approaches. Everything produces the same error. I've also tried giving the pod owner permissions on the volume itself using cloud tools and nothing seems to work.

What is this issue and how can it be resolved?

**Comment by antonlisovenko** [comment]
hi @jatalocks 

This error means that the volume has been mounted in readonly mode. We encountered it initially in AWS when we didn't set `security.fsGroup` setting. In Openshift though `security` shouldn't be set at all as it's supposed to manage this by itself - that's why `MANAGED_SECURITY_CONTEXT` environment variable must be set for the Operator when it's installed in Openshift.
Currently in non-Openshift environments the Operator sets `securityContext.fsGroup: 2000` for podTemplate spec and `securityContext.runAsUser: 2000` for container spec. This works for AWS but may not work for other environments.

This could be the area you could play in - can you try changing the `securityContext` values to something else? You can override the values set by the Operator using custom `podTemplate`: https://github.com/mongodb/mongodb-enterprise-kubernetes/tree/master/samples/mongodb/pod-template.

Check our docs: https://docs.mongodb.com/kubernetes-operator/master/tutorial/modify-resource-image/

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
