### ISSUE TITLE
Community vs Enerprise Opperator

### ISSUE THREAD

**Issue by kaykhancheckpoint** [mongodb/mongodb-enterprise-kubernetes#122]
What are the main difference between the community operator vs enterprise operator?

Is there an outline of things i should know before deciding on whether to use the community vs the enterprise version? For example is the enterprise version some paid service?

**Comment by theburi** [comment]
Community Operator is an open-source project that was just started. It has some limited feature set and it is been worked on extensively
Enterprise Version has a much more extensive feature list and comes with MongoDB Enterprise subscription. 
The best way to compare two versions is through our documentation or get in touch with our sales teams
https://docs.mongodb.com/kubernetes-operator/master/
https://github.com/mongodb/mongodb-kubernetes-operator

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
