### ISSUE TITLE
After deleting a replica set with an active backup, alerts for the Ops Manager project are still enabled

### ISSUE THREAD

**Issue by ItayZviCohen** [mongodb/mongodb-enterprise-kubernetes#128]
In recent release you've introduced Ops Manager project persistence when backup is active for the replicaset, but after deleting the replica set project alerts are still enabled, so a lot of alert emails are sent to project users.
Can you please make the operator disable the alerts for the project after it deleted the replica set ?
Thanks,
Itay

**Comment by ItayZviCohen** [comment]
In recent release you've introduced Ops Manager project persistence when back is active for the cluster, but after deleting the replica set project alerts are still open, so a lot of alert emails are sent to project users.
Can you please make the operator disable the alerts for the project after it deleted the replica set ?
Thanks,
Itay

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
