### ISSUE TITLE
Changing the "app" label of the stateful set

### ISSUE THREAD

**Issue by ItayZviCohen** [mongodb/mongodb-enterprise-kubernetes#132]
Hey, how can I change the 'app' label for the MongoDB database resource's stateful set?

**Comment by ItayZviCohen** [comment]
Anyone? Is there such feature?

**Comment by chatton** [comment]
Hi @ItayZviCohen 

It is currently only possible to modify arbitrary options of the StatefulSet's podTemplateSpec via `.spec.podSpec.podTemplate`, currently there is no way of modifying the labels of the StatefulSet itself.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
