### ISSUE TITLE
No Monitoring detected. Many features will not function correctly without Monitoring enabled. Visit the Servers View to enable Monitoring on an existing Server.

### ISSUE THREAD

**Issue by zouchengli** [mongodb/mongodb-enterprise-kubernetes#134]
![image](https://user-images.githubusercontent.com/27568522/91149000-19a36e00-e6ed-11ea-84b9-0e9657c2af56.png)

**Comment by zouchengli** [comment]
Installed ops manager on kuberneters version v1.13.12

**Comment by chatton** [comment]
Hi @zouchengli  thanks for the report,

A misconfiguration of the backing AppDB is a known issue right now when TLS is configured. Do you currently have TLS configured via `spec.applicationDatabase.security.tls`? 

The TLS misconfiguration will be fixed in the next release of the operator.

The other issue you created #133 looks to also be a side product of this same issue and should be resolved at the same time.

**Comment by zouchengli** [comment]
> Hi @zouchengli thanks for the report,
> 
> A misconfiguration of the backing AppDB is a known issue right now when TLS is configured. Do you currently have TLS configured via `spec.applicationDatabase.security.tls`?
> 
> The TLS misconfiguration will be fixed in the next release of the operator.
> 
> The other issue you created #133 looks to also be a side product of this same issue and should be resolved at the same time.

Ok,I know thank you.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
