### ISSUE TITLE
Update featureCompatibilityVersion in docs

### ISSUE THREAD

**Issue by NickSchleicher** [mongodb/mongodb-enterprise-kubernetes#137]
docs only related issue:

https://docs.mongodb.com/kubernetes-operator/master/tutorial/upgrade-mdb-version/
will tell you how to set the featureCompatibilityVersion when upgrading, i had to quote this number to work after getting this error

```
error: mongodb.mongodb.com "mongodb" could not be patched: admission webhook "mdbpolicy.mongodb.com" denied the request: unmarshalerDecoder: json: cannot unmarshal number into Go struct field MongoDbSpec.spec.featureCompatibilityVersion of type string
```

`featureCompatibilityVersion: 4.0`
->
`featureCompatibilityVersion: "4.0"`

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
