### ISSUE TITLE
Ops-Manager x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by vikasjella26** [mongodb/mongodb-enterprise-kubernetes#143]
I'm trying to deploy Ops-manager in Kubernetes cluster via MongoDB Kubernetes Operator. I used openssl for generating self-signed certificates and configured in Ops-manager deployment following [](https://docs.mongodb.com/kubernetes-operator/master/tutorial/deploy-om-container/)). 

I generated a self-signed certificate using openssl for Ops-manager URL: ops-manager-svc.mongodb.svc.cluster.local

After deploying the ops-manager one of the ApplicationDB is (0/1) Running state and I've checked the logs. It's showing like

`{"logType":"automation-agent-verbose","contents":"[2020/09/29 14:50:25.188] [.error] [cm/director/director.go:mainLoop:379] <ops-manager-db-2> [14:50:25.188] Failed to planAndExecute : <ops-manager-db-2> [14:50:25.188] Plan execution failed on step Download as part of move Download : <ops-manager-db-2> [14:50:25.188] Failed to apply action. Result = <nil> : <ops-manager-db-2> [14:49:55.188] Error downloading url=https://downloads.mongodb.com/linux/mongodb-linux-x86_64-enterprise-ubuntu1604-4.2.6.tgz to /var/lib/mongodb-mms-automation/downloads/mongodb-linux-x86_64-4.2.6-ent : <ops-manager-db-2> [14:49:55.188] Error downloading url=https://downloads.mongodb.com/linux/mongodb-linux-x86_64-enterprise-ubuntu1604-4.2.6.tgz : resp=<nil> : Get https://downloads.mongodb.com/linux/mongodb-linux-x86_64-enterprise-ubuntu1604-4.2.6.tgz: x509: certificate signed by unknown authority"}`

What might be wrong here?

**Comment by theburi** [comment]
Hi. The issue is that a connection to download the correct MongoDB binary can not be established as MongoDB Agent uses a different CA. (https://downloads.mongodb.com is not trusted by Agent connection). There are two options here. 1. Add Root CA to custom signed CA. Concatenate them together 2. Enable Hybrid mode in Ops Manager so that Agents will proxy downloads via opsManager. (configuration.automation.versions.source: "hybrid" ) https://docs.opsmanager.mongodb.com/current/reference/configuration/#automation.versions.source

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
