### ISSUE TITLE
Unable to assign Data Access to LDAP user

### ISSUE THREAD

**Issue by techBeck03** [mongodb/mongodb-enterprise-kubernetes#148]
**Bug Description**
I've deployed Ops Manager via the kubernetes operator and configured it to use LDAP user authentication.  I'm able to login and do global admin tasks using my ldap credentials.  What i'm struggling to figure out is how to add an LDAP user to a project and assign permissions to things like Data Access within a project.  When i go to assign users to a project the User list is empty and I can't find a way to manually add.

**Environment Info**
Kubernetes Operator: 1.8.0
Ops Manager Version: 4.4.4

Any help is much appreciated!

**Comment by bznein** [comment]
Hello @techBeck03,

I'm not sure I understand the issue, but let me try and see if I can help. Following this guide: https://docs.mongodb.com/kubernetes-operator/v1.8/reference/k8s-operator-specification/#security-settings you should be able, for a specific project, to create custom roles each with its own set of privileges.

Then, through https://docs.mongodb.com/kubernetes-operator/v1.8/reference/k8s-operator-specification/#spec.security.authentication.ldap.userToDNMapping and https://docs.mongodb.com/kubernetes-operator/v1.8/reference/k8s-operator-specification/#spec.security.authentication.ldap.authzQueryTemplate you should be able to map your LDAP user to a specific role you defined.

Let me know if this helps!

Nikolas

**Comment by techBeck03** [comment]
Maybe i'm confusing Ops Manger permissions with Database permissions but what i'm trying to access is the Data Explorer within a project within the Ops Manager UI.  I've edited the LDAP mappings for my project so that my LDAP group is every kind of admin for that project but I still get `You are not authorized to use Data Explorer.` when i try to access Data Explorer.

When i go to Access Manager for that project or even the organization it lives in there are no users listed and no ability to invite/add a member.  I assume this is because i'm defining this via LDAP but then i don't understand why Data Explorer isn't working.

Thanks!

**Comment by theburi** [comment]
In order to use Data Explorer, you need OpsManager access as described here https://docs.opsmanager.mongodb.com/current/data-explorer/
You actually don't need DB access as a DB query is done by MongoDB Automation Agent user.

By the error message, it looks like the OpsManager user does not have one of the required permissions.
I would advise raising a support Case with MongoDB if setting these permissions do not help.

**Comment by techBeck03** [comment]
> In order to use Data Explorer, you need OpsManager access as described here https://docs.opsmanager.mongodb.com/current/data-explorer/
> You actually don't need DB access as a DB query is done by MongoDB Automation Agent user.
> 
> By the error message, it looks like the OpsManager user does not have one of the required permissions.
> I would advise raising a support Case with MongoDB if setting these permissions do not help.

Thanks!  I tried using assigning every permission i could to my LDAP role but it seems like Ops manager doesn't honor those permissions within Data Explorer.  I finally just changed my Authentication strategy to `Application Database` and everything worked fine using local users.

I will try opening a case if that is the proper path to take.  I was thinking this looks more like a software bug but maybe it's a user bug.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
