### ISSUE TITLE
MongoDB Operator 1.8 for Red Hat OpenShift is missing instructions for Ops Manager

### ISSUE THREAD

**Issue by alberttwong** [mongodb/mongodb-enterprise-kubernetes#152]
I'll submit a PR on this later but for the Ops Manager, you need to create the admin user account kube secret for Ops Manager (https://docs.mongodb.com/kubernetes-operator/stable/tutorial/plan-om-resource/#om-rsrc-prereqs)  before you provision it.

Need to insert text right before "required parameters"
 
<img width="1026" alt="Screen Shot 2020-10-22 at 11 27 17 PM" src="https://user-images.githubusercontent.com/749093/96963865-48a44900-14be-11eb-9ebe-151d717d88f1.png">

**Comment by alberttwong** [comment]
Also Ops Manager can only be installed in the "openshift-operators" namespace.   The reason why is that all the service accounts are in  "openshift-operators" namespace per default install.    Need to add that text into the docs.

**Comment by jamesbroadhead** [comment]
@alberttwong  thanks for finding this - looking forward to your PR!

**Comment by alberttwong** [comment]
Sorry.  This is dumb but I can't find where that text is stored.

**Comment by alberttwong** [comment]
I was told that I need to do this through docs team using JIRA.

**Comment by alberttwong** [comment]
https://jira.mongodb.org/browse/DOCS-13948

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
