### ISSUE TITLE
Cant create OpsManager Admin User

### ISSUE THREAD

**Issue by deamon1386** [mongodb/mongodb-enterprise-kubernetes#167]
I have installed Operator version 1.8 and installed OpsManager spec database version 4.4.5 and am getting the following error.  

message: 'Failed to create an admin user in Ops Manager: Status: 500 (Internal
        Server Error), ErrorCode: UNEXPECTED_ERROR, Detail: Unexpected error.'
      phase: Failed
      url: http://opsmanager-svc.mongo-dev.svc.cluster.local:8080

I verified the secrets are setup according to the DOC's but cant create an admin user to log into the OpsManger.

**Comment by deamon1386** [comment]
Looks like I found the issue.  When I changed persistent to false I was able to create an admin user.

**Comment by theburi** [comment]
Hi there could be few issues. 1. when you delete CRD, PV's are left behind. So if you could clean them up to do a proper brand new install. What happens is that old Database left behind; 2. Sometimes it may take 15 min to start up OpsManager STS at it runs a lot for pre-flight/consistency checks.

**Comment by deamon1386** [comment]
As soon as I added the following to my manager yaml it built successfully within 2 minutes. 

    additionalMongodConfig:
      operationProfiling:
        mode: slowOp
    podSpec:
      cpu: '0.25'

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
