### ISSUE TITLE
TLS Certificate Error

### ISSUE THREAD

**Issue by vikasjella26** [mongodb/mongodb-enterprise-kubernetes#169]
I'm trying to generate the self-signed certificates for Mongodb deployed by Mongodb operator 1.8. 
Followed the appendix A, Appendix B to create CA and CRT and Key files.
https://docs.mongodb.com/manual/appendix/security/appendixB-openssl-server/
And followed the mongodb documentation (https://docs.mongodb.com/kubernetes-operator/v1.8/tutorial/deploy-om-container) to configure the ops-manager.
But when I try to  
a. Obtain the entire TLS certificate chain from downloads.mongodb.com. The following openssl command outputs each certificate in the chain to your current working directory, in .crt format:

/usr/local/opt/openssl/bin/openssl s_client -showcerts -verify 2 \
-connect downloads.mongodb.com:443 < /dev/null \
| awk '/BEGIN/,/END/{ if(/BEGIN/){a++}; out="cert"a".crt"; print >out}'

getting following error:
verify depth is 2
140641188005776:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:

What might be the wrong.

**Comment by Panos512** [comment]
+1

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
