### ISSUE TITLE
Mongos and config pods are restarted from time to time, how can I find out why?

### ISSUE THREAD

**Issue by cinaradem** [mongodb/mongodb-enterprise-kubernetes#173]
hi,
Mongos and config pods are restarted from time to time, how can I find out why?

<img width="1138" alt="Screen Shot 2020-12-27 at 17 14 07" src="https://user-images.githubusercontent.com/4299460/103172780-f3dad100-4866-11eb-86ab-d3134af236f6.png">

**Comment by antonlisovenko** [comment]
hi @cinaradem , can you check the events for the pods to see when and why they were restarted?

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
