### ISSUE TITLE
Ops Manager deployment fails to finalize initialization when configured to use LDAP

### ISSUE THREAD

**Issue by ZegalPL** [mongodb/mongodb-enterprise-kubernetes#178]
Hello,

I am facing an issue when deploying ops manager with LDAP configured. 

I have `mms.ignoreInitialUiSetup: "true"` and `mms.userSvcClass: "com.xgen.svc.mms.svc.user.UserSvcLdap"`, and rest of relevant configuration parameters, when i run the deployment i can see all resources deployed properly (running state) and I am able to login to Ops Manager GUI with my LDAP account, however ops-manager-db replica set is not visible, mongodb-enterprise-operator logs report that ops manager init is not reaching conclusion; it tries to create initial admin user from secret, and fails to do so with below error:

`Failed to create an admin user in Ops Manager: Status: 403 (Forbidden), ErrorCode: INVITATION_ONLY_MODE_OR_LDAP`

Despite my secret being populated with working LDAP username and password. I suppose that init script invokes `POST /unauth/users` api call which fails since we do not have the possibility to mange users with ops manage when LDAP is enabled.  I  tried to remove `adminCredentials` parameter from my yaml altogether , but got different error:

`The secret *** doesn't exist - you need to create it to finish Ops Manager initialization`

both messages seem to cause initialization infinite retires.

How can i proceed from there? I would expect to be able to properly deploy ops manager with LDAP enabled from the start.

Best Regards, Piotr

**Comment by alberttwong** [comment]
I'd recommend you open a ticket with MongoDB support.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
