### ISSUE TITLE
Ability to add annotations to pods

### ISSUE THREAD

**Issue by kurktchiev** [mongodb/mongodb-enterprise-kubernetes#19]
It would be fantastic if we have the ability to pass pod annotations down to the operator which will then pass them down to the pods it spins up. 

For example, if I want to add special annotation to my RS pods that allows other services running in the cluster to find the mongo instance. Or if I use annotations to add extra functionality to the pods on my cluster, etc.

Basically, I should be able to annotate the pods that the operator spins up. The annotations added to the CRD manifest only apply to the CRD definition not the newly spun up pods.

**Comment by antonlisovenko** [comment]
Thanks @kurktchiev for this feature request, I've created an internal ticket CLOUDP-39918 for this and we'll see if we need this functionality and when we have time to implement it

**Comment by antonlisovenko** [comment]
This feature will be implemented as a part of CLOUDP-31700 which will allow to set custom pod template fields

**Comment by Hugome** [comment]
Is the CLOUDP-31700 will allow to set custom memory limits/requests ?
Because for the moment ops-manager/ops-manager-backup statefulset has only a memory limit of 5G. And the behavior in this case is to copy the limits onto the requests (https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/#what-if-you-specify-a-container-s-limit-but-not-its-request)
And 5G for a backup daemon is a little too much in some cases.
If yes, any update on this internal ticket ?
Thanks

**Comment by antonlisovenko** [comment]
custom pod parameters can be set for `MongoDB` only at the moment.
We plan to support `podSpec` for `MongoDBOpsManager` by the next release of the Operator.

This ticket can be closed as annotations are supported as of Operator 1.4.2
