### ISSUE TITLE
How do I connect to the Mongo DB ?

### ISSUE THREAD

**Issue by sbose78** [mongodb/mongodb-enterprise-kubernetes#29]
Hi, Now that the operator creates the pods/service, how do I connect to the DB from my app?

**Comment by antonlisovenko** [comment]
hi @sbose78 if your application is deployed inside kubernetes - you can follow the common pattern of connecting to mongodb using mongo url: https://docs.mongodb.com/manual/reference/connection-string/
Just use the FQDNs in the format Kubernetes generates them (pod_name.service_name...)

**Comment by antonlisovenko** [comment]
Thanks for the idea, created the CLOUDP-51462 for internal tracking, we'll discuss this with the team.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
