### ISSUE TITLE
Resource Validation should not exist in the CSV

### ISSUE THREAD

**Issue by OchiengEd** [mongodb/mongodb-enterprise-kubernetes#35]
The section `.spec.customresourcedefinitions.owned` of the cluster service version(or CSV) includes the validation for the Custom Resource Definitions(CRD). These sections should only be present in the CRD.

See the blocks hightlighted below:

https://github.com/operator-framework/community-operators/blob/bbe26829932c8c968a1a86b15797fd933846c89b/upstream-community-operators/mongodb-enterprise/mongodb-enterprise.v1.1.0.clusterserviceversion.yaml#L167-L297

https://github.com/operator-framework/community-operators/blob/bbe26829932c8c968a1a86b15797fd933846c89b/upstream-community-operators/mongodb-enterprise/mongodb-enterprise.v1.1.0.clusterserviceversion.yaml#L305-L337

This issue affects `v1.2.1`, `v1.2.2` and `v1.2.3` CSVs as well.

**Comment by antonlisovenko** [comment]
thanks @OchiengEd  for your report, created CLOUDP-51461 to track this issue internally

**Comment by theburi** [comment]
This issue has been resolved.
@OchiengEd please let us know if it ok to close.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
