### ISSUE TITLE
Deploy PSA (primary-secondary-arbiter) clusters with Operator

### ISSUE THREAD

**Issue by andrii-litvinov** [mongodb/mongodb-enterprise-kubernetes#43]
I need to deploy Mongo cluster across two data centers and be able to survive a loss of the entire DC. For such scenario the doc https://docs.mongodb.com/manual/core/replica-set-architecture-geographically-distributed/ suggests to host arbiter node in the cloud. How can I tell Operator to create an arbiter node and host it in the cloud?

If that's not currently possible, do you plan to allow arbiter nodes creation? Or is there a way to assign 0 priority to the node hosted in the cloud?

**Comment by antonlisovenko** [comment]
Hi.
For any configurations which are not covered by the Operator you can you Ops/Cloud Manager UI for the Deployment
The Mongodb Operator won't override such settings.

**Comment by andrii-litvinov** [comment]
Thank you for a quick reply!

I tried to set priority to the member and it worked, but I still not sure how to set a priority to the member that runs in specific cluster node. Probably that has to be assigned after the member is scheduled to specific knows node.

Also I tried to change node from Default to Arbiter and got following exception:

> Invalid config: Arbiter state may not change for members. Detected the following change: PROCESS parameter isArb changed from false to true

So it seems that I neither can change the role of the node nor can add a new Arbiter node because in that case I receive error

> Change not allowed: Only MongoDB Enterprise Kubernetes Operator can add or remove members to the shards

Is there any other way to assign Arbiter role to the node (as it is our preferred solution)?

**Comment by antonlisovenko** [comment]
right, seems converting a secondary to an arbiter cannot be done automatically due to Mongodb restriction.
Adding a member to a replica set is forbidden - there is a workaround (remove "externallyManaged" tag for the project to allow manual editing of the "Operator owned" fields) but it won't last long as the Operator tries to "fix" the tag on each reconciliation and the unknown member will be gone as well.

Not sure there is an easy way to get an arbiter, I've created an internal ticket to track this, but I doubt we'll have time in nearest future to address this.

**Comment by andrii-litvinov** [comment]
Alright, thanks for the update, we will try to see what our options are.

**Comment by andrii-litvinov** [comment]
Hi @antonlisovenko, it's been a month since I created this issue. Do you have an update on arbiter feature? Can we expect it sometime soon?

**Comment by theburi** [comment]
Hi. Our current Operator does not support deploying Mongodb clusters between across clusters. PSA is usually used when MongODB has to be deployed across geo-distributed clusters.  Withing single K8s cluster three-member replica is a recommended configuration. 
Our plan to support Arbiters when we support Multicluster Federation sometime next year.
I logged this request here to gauge interest in this configuration. https://feedback.mongodb.com/forums/924355-ops-tools/suggestions/39005791-support-arbiters-with-mongodb-kubernetes-operator

**Comment by andrii-litvinov** [comment]
Thank you @theburi. Yes, we have single k8s cluster with nodes in two data centers and we would like to be able to deploy arbiter to the node hosted in cloud, which will be part of the same k8s cluster as well.

**Comment by theburi** [comment]
@andrii-litvinov  we are about to start working on this item https://feedback.mongodb.com/forums/924355-ops-tools/suggestions/39654730-deploy-mongodb-across-different-kubernetes-cluster
It will be adding PSA configuration as part fo that work. We will keep updating our progress in that link.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
